services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: oclus
      POSTGRES_USER: oclus
      POSTGRES_PASSWORD: oclus
    ports: [ "5432:5432" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports: [ "1025:1025", "8025:8025" ]

volumes:
  postgres_data:
