[package]
name = "oclus-server"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { version = "2.0" }
anyhow = { version = "1.0" }
log = { version = "0.4" }
env_logger = { version = "0.11" }

actix-web = { version = "4.9" }
